name: Verificacion Diaria de Sitios Web

on:
  schedule:
    # 7:30 AM local (11:30 AM UTC)
    - cron: '30 11 * * *' 

    # 1:00 PM local (5:00 PM UTC)
    - cron: '00 17 * * *'

  workflow_dispatch:

jobs:
  check-websites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: Ejecutar y Preparar Reporte para Telegram
        id: generate_report
        run: |
          # 1. Obtener la fecha y hora de la ejecuci칩n, ajustada a UTC-4 (tu hora local)
          # Esto garantiza que el reporte muestre la hora correcta (ej: 7:30 AM o 1:00 PM).
          # Usamos "TZ='America/Caracas'" para forzar el huso horario.
          FECHA_HORA_LOCAL=$(TZ='America/Caracas' date +"%Y-%m-%d %H:%M %p %Z")
          
          # 2. Ejecuta el script de verificaci칩n y guarda TODA la salida
          python verificar_webs.py > full_report.txt
          
          # 3. Construye el encabezado del mensaje con la fecha y hora din치mica
          TITULO_MENSAJE="*Reporte de Sitios Web del ${FECHA_HORA_LOCAL}*"
          
          # 4. Prepara el cuerpo del mensaje (primeras 15 l칤neas del reporte)
          # Escapa saltos de l칤nea (\n) a %0A y comillas (")
          REPORTE_CUERPO=$(cat full_report.txt | head -n 15 | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/%0A/g')
          
          # 5. Combina el t칤tulo y el cuerpo del mensaje
          MENSAJE_COMPLETO="${TITULO_MENSAJE}%0A%0A${REPORTE_CUERPO}"
          
          # 6. Hace la variable del mensaje completa disponible para el siguiente paso
          echo "TELEGRAM_MESSAGE=$MENSAJE_COMPLETO" >> $GITHUB_ENV
          
          # 7. Imprime el reporte completo en los logs de GitHub
          cat full_report.txt

      - name: Enviar Notificaci칩n a Telegram 游눫
        run: |
          echo "Enviando reporte a Telegram..."
          
          # Llama a la API de sendMessage, usando la variable de entorno que contiene
          # el t칤tulo din치mico y el cuerpo.
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="${{ env.TELEGRAM_MESSAGE }}" \
          -d parse_mode=Markdown